---

- name: Parse config
  become: true
  script: ../common/files/openstack-config-parser.py heat
  ignore_errors: true
  register: heat_data

- name: setting fact
  set_fact:
    stockpile_openstack_heat: "{{ heat_data.stdout }}"
  when: heat_data.stdout is defined
