---

- name: Get max_connections on the database
  shell: mysql -e "show variables like 'max_connections';" | grep max_connections | awk '{print $2}'
  register: max_conn
  ignore_errors: true
  when: hostvars[inventory_hostname]['containers'] is not defined

- name: Set max database connections
  set_fact:
    stockpile_openstack_mysql_max_connections="{{ max_conn.stdout }}"
  when: max_conn is succeeded

# This doesn't work for downstream as mysql isn't containerized on RHOSP
# at least RHOSP13 uses mariadb so will need changes
# NEEDS TO BE FIXED
- name: Get max_connections on the database
  shell: docker exec mysql cat /etc/my.cnf.d/galera.cnf| grep max_connections | awk -F ' = ' '{print $2}'
  register: max_conn
  ignore_errors: true
  when: hostvars[inventory_hostname]['containers'] is defined

- name: Set max database connections
  set_fact:
    stockpile_openstack_mysql_max_connections="{{ max_conn.stdout }}"
  when: max_conn is succeeded

- name : Get file descriptors for the mysql process
  shell: cat /proc/$(pgrep mysqld_safe)/limits | grep "open files" | awk '{print $4}'
  register: mysql_desc
  ignore_errors: true

- name: set file descriptors
  set_fact:
    stockpile_openstack_file_descriptors="{{ mysql_desc.stdout }}"
  when: mysql_desc is succeeded
