---
  - name: check node
    command: kubectl cluster-info
    register: cluster_status
    ignore_errors: true

  - block:
    
    - name: Get info
      community.kubernetes.k8s_info:
        kind: ConfigMap
      register: item_list

    - name: Set info as facts
      set_fact:
        stockpile_k8s_configmaps: "{{ item_list.resources }}"

    when: cluster_status is succeeded
