- name: slurp OpenStack release file
  slurp:
    src: /etc/rhosp-release
  register: rhosp_release

- name: Set fact for OpenStack release
  set_fact:
    stockpile_rhosp_overcloud_release: "{{ rhosp_release['content'] | b64decode  }}"
  ignore_errors: true

- name: Get ovs version
  shell: ovs-vsctl --version | grep vSwitch | awk {'print$4'}
  register: ovs_version
  ignore_errors: true

- name: Set ovs version fact
  set_fact:
    stockpile_osp_overcloud_ovs_version: "{{ ovs_version.stdout }}"
  when: ovs_version.rc == 0
