---

- name: Parse config
  become: true
  script: ../common/files/openstack-config-parser.py gnocchi
  ignore_errors: true
  register: gnocchi_data

- name: setting fact
  set_fact:
    stockpile_openstack_gnocchi: "{{ gnocchi_data.stdout }}"
  when: gnocchi_data is succeeded
